# Compile components library
set(IDYLLA_COMPONENTS_SRC ${CMAKE_CURRENT_SOURCE_DIR})
set(IDYLLA_COMPONENTS_DIRECTORY ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/components)
set(IDYLLA_COMPONENTS_FILE "${IDYLLA_COMPONENTS_DIRECTORY}/${COMPONENT_LIB}")

file(MAKE_DIRECTORY ${IDYLLA_COMPONENTS_DIRECTORY})

add_custom_target(${PROJECT_NAME} ALL
                  compilelib ${IDYLLA_COMPONENTS_SRC} ${IDYLLA_COMPONENTS_FILE}
                  WORKING_DIRECTORY ${IDYLLA_COMPONENTS_DIRECTORY}
                  DEPENDS compilelib)

install(FILES ${IDYLLA_COMPONENTS_FILE} DESTINATION ${INSTALL_COMPONENTS_PATH} COMPONENT library)
